### Create Patient
###
POST http://localhost:8089/api/add
Content-Type: application/json

{
  "name": "Devvrat Tiwari",
  "email": "hs1255@gmail.com",
  "address": "Rasuliya Hbad",
  "birthDate": "1993-04-04",
  "phoneNumber": "+917898484812",
  "registerDate": "2025-10-19"
}
