### Create Patient
###
POST http://localhost:8089/api/add
Content-Type: application/json

{
  "name": "Kabir Singh",
  "email": "kabir.singh87@gmail.com",
  "address": "New Delhi",
  "registerDate": "2023-02-25",
  "birthDate": "1995-01-05",
  "phoneNumber": "+917700889944"
}