### Create Patient
###
POST http://localhost:8089/api/add
Content-Type: application/json

{
  "name": "Piyush lendi",
  "email": "piyushLendiji1233@juetguna.in",
  "address": "Meenakshi I",
  "registerDate": "2023-01-21",
  "birthDate": "2005-10-03",
  "phoneNumber": "+918898151222"
}

