### Updates an exixting patient

PUT http://localhost:8089/api/update/3e77f79c-d99b-44b1-9328-a6f0c582cbb7
Content-Type: application/json

{

  "address": "Bharat Colony Madan Mahal",
  "birthDate": "1999-06-20",
  "phoneNumber": "+919893600809",
  "email": "devvratrendu123@gmail.com"

}
